name: thesis-niels_repo
channels:
  - pytorch
  - nvidia
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python-dotenv
  - pyyaml
  - scikit-learn
  - scipy
  - pytorch=2.4
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # requires the nvidia channel
  - pip:
      - black==25.9.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - nbstripout==0.8.1
      - pre_commit==4.3.0
      - pytest==8.4.2
      - rich==14.2.0
      - ruff==0.14.0
      - wandb==0.22.2
      - -e .
