name: thesis-ml
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch
  - cpuonly
  - numpy
  - matplotlib
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - hydra-core
      - omegaconf
      - pytest
      - black
      - ruff
