latent_dim: 32
codebook_size: 512
enc_hidden: [128, 128]
dec_hidden: [128, 128]
dropout: 0.0
activation: "gelu"
beta: 0.25
ema: true
ema_decay: 0.99

id_embed_dim: 8        # embedding size for obj_id

# globals head (tiny MLP AE)
globals_head: true
globals_hidden: [32]
globals_beta: 1.0      # weight of globals recon in total loss

# optional id classification auxiliary loss
id_ce_beta: 0.0
