executable              = tests/stoomboot/test_gpu.sh
initialdir              = /project/atlas/users/nterlind/Thesis-Code

log     = /data/atlas/users/nterlind/logs/test_gpu.$(ClusterId).$(ProcId).log
output  = /data/atlas/users/nterlind/logs/test_gpu.$(ClusterId).$(ProcId).out
error   = /data/atlas/users/nterlind/logs/test_gpu.$(ClusterId).$(ProcId).err

request_cpus   = 2
request_memory = 8G
request_gpus   = 1
request_disk   = 2GB
+UseOS         = "el9"
+JobCategory   = "short"

# give apptainer a writable cache (pre-create this dir once)
environment = "APPTAINER_CACHEDIR=/data/atlas/users/nterlind/.apptainer_cache"
queue 1
