universe      = vanilla
executable    = hpc/stoomboot/report.sh
arguments     =

initialdir    = /project/atlas/users/nterlind/Thesis-Code

output        = /data/atlas/users/nterlind/logs/stdout/report_$(ClusterId).$(ProcId).out
error         = /data/atlas/users/nterlind/logs/stderr/report_$(ClusterId).$(ProcId).err
log           = /data/atlas/users/nterlind/logs/stdlog/report_$(ClusterId).log

request_cpus  = 1
request_memory = 8GB
request_disk  = 8GB

+UseOS = "el9"
+JobCategory = "short"
should_transfer_files = NO
getenv        = True
stream_output = True
stream_error  = True

queue 1
